# This workflow runs on Pull Requests opened against MAIN.
# It will scan the incoming HEAD branch with Workbench.
# If Pending IDs or Policy Violations are found, the PR will be blocked.

name: Scan Diff of Incoming PRs

on: 
  pull_request:
    branches: 
      - main

jobs:
  workbench-scan:
    runs-on: ubuntu-latest
    env:
      WORKBENCH_URL: ${{ secrets.WORKBENCH_URL }}
      WORKBENCH_USER: ${{ secrets.WORKBENCH_USER }}
      WORKBENCH_TOKEN: ${{ secrets.WORKBENCH_TOKEN }}

    steps:
      - name: Checkout Workbench CLI
        uses: actions/checkout@v4
        with: 
          repository: tomgonzo/workbench-cli
          path: fossid-tools

      - name: Install Workbench CLI
        run: pip install ./fossid-tools

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Scan Files Changed by PR
        run: |
          workbench-cli scan-git-diff \
            --project-name $GITHUB_REPOSITORY \
            --scan-name Diff-$GITHUB_HEAD_REF \
            --base-ref $GITHUB_BASE_REF \
            --compare-ref $GITHUB_HEAD_REF \
            --run-dependency-analysis \
            --autoid-file-licenses \
            --autoid-file-copyrights \
            --id-reuse \
            --id-reuse-type project \
            --id-reuse-source $GITHUB_REPOSITORY \
            --no-wait \
            --show-scan-metrics

      - name: Evaluate Gates
        run: |
          workbench-cli evaluate-gates \
          --project-name $GITHUB_REPOSITORY \
          --scan-name Diff-$GITHUB_HEAD_REF \
          --fail-on-pending \
          --fail-on-policy
