# This workflow runs on Pull Requests opened against MAIN.
# It will scan only those files touched by the incoming HEAD branch.
# If Pending IDs or Policy Violations are found, the PR will be blocked.

name: Scan Diff of Incoming PRs

on: 
  pull_request:
    branches: 
      - main

jobs:
  workbench-scan:
    runs-on: ubuntu-latest
    env:
      WORKBENCH_URL: ${{ secrets.WORKBENCH_URL }}
      WORKBENCH_USER: ${{ secrets.WORKBENCH_USER }}
      WORKBENCH_TOKEN: ${{ secrets.WORKBENCH_TOKEN }}

    steps:
      - name: Checkout Target Repo
        uses: actions/checkout@v4
        with:
          path: target-repo
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Fetch Base and Head Branches
        working-directory: target-repo
        run: |
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
          git fetch origin ${{ github.head_ref }}:${{ github.head_ref }}
          git branch -a
      
      - name: Scan Files Changed by PR
        run: |
          docker run \
          -v $GITHUB_WORKSPACE/target-repo:/scan_target \
          -w /scan_target \
          ghcr.io/tomgonzo/workbench-cli:latest \
          --api-url ${{ env.WORKBENCH_URL }} \
          --api-user ${{ env.WORKBENCH_USER }} \
          --api-token ${{ env.WORKBENCH_TOKEN }} \
          scan-git-diff \
          --project-name $GITHUB_REPOSITORY \
          --scan-name Diff-$GITHUB_HEAD_REF \
          --base-ref ${{ github.base_ref }} \
          --compare-ref ${{ github.head_ref }} \
          --run-dependency-analysis \
          --autoid-file-licenses \
          --autoid-file-copyrights \
          --show-scan-metrics
    
      - name: Evaluate Gates
        run: |
            docker run ghcr.io/tomgonzo/workbench-cli:latest \
            --api-url ${{ env.WORKBENCH_URL }} \
            --api-user ${{ env.WORKBENCH_USER }} \
            --api-token ${{ env.WORKBENCH_TOKEN }} \
            evaluate-gates \
            --project-name $GITHUB_REPOSITORY \
            --scan-name Diff-$GITHUB_HEAD_REF \
            --fail-on-pending \
            --fail-on-policy 
