# .github/workflows/linters.yml
name: lint

# Run on pushes and pull requests targeting the main branches
on:
  push:
    branches: [ main ] # Adjust branch names if needed
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
  
jobs:
  code_linting:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4 # Use a recent version

      # 2. Set up Python (only need one version for linting)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Use a single recent version

      # 3. Install Linters
      - name: Install Linters
        run: |
          python -m pip install --upgrade pip
          # Install linters directly, no need for requirements.txt or installing the project
          pip install pycodestyle pylint

      # 4. Run Linters on the source code directory
      - name: Run Linters
        run: |
          # Lint the package source directory inside 'src' - only check for critical errors
          # Ignore style warnings for now, focus on syntax errors and critical issues
          pycodestyle src/workbench_cli/ --ignore=W291,W293,E501,E111,E117,E128,E129,E261,E266,E302,E303,E201,E202,E701,W504,E226,E402,E114 --max-line-length=120
          # Run pylint with only errors, no warnings
          pylint --errors-only --rcfile .pylintrc src/workbench_cli/
