# .github/workflows/tests.yml
name: Run Tests

# Run on pushes and pull requests targeting the main branches
on:
  push:
    branches: [ main ] # Adjust branch names if needed
  pull_request:
    branches: [ main ]

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . pytest pytest-xdist pytest-mock
      - name: Run all unit tests
        run: pytest tests/unit/ -v --tb=short

  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [unit_tests]
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . pytest pytest-xdist pytest-mock
      - name: Run integration tests
        run: pytest tests/integration/ -v